
# include: package:flutter_lints/flutter.yaml
# include: package:lint/analysis_options.yaml
analyzer:
  errors:
    use_build_context_synchronously: ignore
    constant_identifier_names: ignore
include: package:flutter_lints/flutter.yaml


linter:
  
  rules:
    # avoid_print: false  # Uncomment to disable the `avoid_print` rule
    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule


