name: flutter_project
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # 状态管理
  provider: ^6.1.2
  # 屏幕适配
  flutter_screenutil: ^5.9.3
  # 网络请求
  dio: ^5.7.0
  # 网络请求日志
  pretty_dio_logger: ^1.4.0
  # toast提示
  oktoast: ^3.4.0
  # 获取版本信息、设备信息等
  package_info_plus: ^8.0.2
  device_info_plus: ^10.1.2
  # 权限申请
  permission_handler: ^11.3.1
  # 跳转外部应用、scheme
  url_launcher: ^6.3.0
  # webview
  webview_flutter: ^4.9.0
  # html显示
  flutter_html: ^3.0.0-beta.2
  # 本地存储
  shared_preferences: ^2.3.2
  # banner轮播图
  flutter_swiper_view: ^1.1.8
  # 下拉加载，上拉刷新
  pull_to_refresh: ^2.0.0
  # webview
  flutter_inappwebview: ^6.1.0+1


dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

  # lint: ^2.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
